import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/_Components/ReactQueryProvider/ReactQueryProvider';
import { Toaster } from 'react-hot-toast';
import NavServer from '@/_Components/Navbar/NavServer';
import getUserProfile from '../../lib/Helper/getUserProfile';
import AsideEmployee from '@/_Components/AsideEmployee/AsideEmployee';
import AsideAdmin from '@/_Components/AsideAdmin/AsideAdmin';

const cairoFont = Cairo({
  variable: '--font-cairo',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Sky Docs',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserProfile();
  return (
    <html
      dir="rtl"
      lang="ar"
      className={`${cairoFont.variable} max-w-[1300px] px-3 ${!user ? 'overflow-hidden' : 'mx-auto'}`}
    >
      <body className={cairoFont.className}>
        <ReactQueryProvider>
          <Toaster />
          <main
            className={`${!user ? '' : 'grid md:grid-cols-[20%_80%] grid-cols-1'} `}
          >
            <div className={`${!user ? 'hidden' : ''} aside`}>
              <div
                className={`aside_employee ${user?.role === 'admin' ? 'hidden' : ''}`}
              >
                <AsideEmployee />
              </div>
              <div
                className={`aside_admin ${user?.role !== 'admin' ? 'hidden' : ''}`}
              >
                <AsideAdmin />
              </div>
            </div>
            <div className="resurt">
              <NavServer />
              {children}
            </div>
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
